"use client";

import { useAuth0 } from "@auth0/auth0-react"; // To display user/tenant info if needed
import React from "react";
import { gql, useQuery } from "@apollo/client";

// Define the GraphQL query to fetch capabilities
// Note: According to your schema.graphql, the query for capabilities
// (and other ArchiMate elements) will be auto-generated by @neo4j/graphql.
// It typically follows the pluralized, camelCased version of the type name.
// We also assume tenantId is handled by the @authorization directive via context.
const GET_CAPABILITIES = gql`
  query GetCapabilities {
    capabilities {
      id
      name
      description
      tenantId
    }
  }
`;

// Interface for the Capability data structure
interface Capability {
  id: string;
  name: string;
  description?: string | null;
  tenantId: string;
}

interface GetCapabilitiesData {
  capabilities: Capability[];
}

export default function CapabilitiesPage() {
  const { isAuthenticated, isLoading: authLoading, user } = useAuth0();
  const { loading, error, data } = useQuery<GetCapabilitiesData>(GET_CAPABILITIES, {
    skip: !isAuthenticated, // Skip query if not authenticated
  });

  if (authLoading || loading) {
    return (
      <div className="container mx-auto p-4">
        <h1 className="text-2xl font-bold mb-4">Capabilities</h1>
        <p>Loading capabilities...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="container mx-auto p-4">
        <h1 className="text-2xl font-bold mb-4">Capabilities</h1>
        <p className="text-red-500">Error fetching capabilities: {error.message}</p>
        <p className="text-sm text-gray-600 mt-2">
          Ensure the Apollo Router and Neo4j Subgraph services are running and correctly configured.
          Also, check the browser console for more details.
        </p>
      </div>
    );
  }

  if (!isAuthenticated) {
    return (
      <div className="container mx-auto p-4">
        <h1 className="text-2xl font-bold mb-4">Capabilities</h1>
        <p>Please log in to view capabilities.</p>
      </div>
    );
  }

  const capabilities = data?.capabilities || [];

  return (
    <div className="container mx-auto p-4">
      <h1 className="text-2xl font-bold mb-6">Capabilities</h1>
      {user && (
        <p className="mb-4 text-sm text-gray-700">
          Viewing capabilities for tenant associated with user: {user.name} ({user.email})
        </p>
      )}
      {capabilities.length === 0 ? (
        <p>No capabilities found for your tenant, or you may not have permission to view them.</p>
      ) : (
        <ul className="space-y-4">
          {capabilities.map((capability) => (
            <li key={capability.id} className="p-4 border border-gray-300 rounded-lg shadow-sm">
              <h2 className="text-xl font-semibold text-blue-600">{capability.name}</h2>
              {capability.description && (
                <p className="text-gray-700 mt-1">{capability.description}</p>
              )}
              <p className="text-xs text-gray-500 mt-2">ID: {capability.id}</p>
              <p className="text-xs text-gray-500">Tenant ID: {capability.tenantId} (Should match context)</p>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
